---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: tomcat-app
spec:
  replicas: {{ .Values.Production.Replicas }}
  template:
    metadata:
      name: tomcat-app
      labels:
        app: tomcat-app
        role: tomcat
        env: production
    spec:
      containers:
      - name: tomcat
        image: {{ .Values.Production.ImageName }}:{{ .Values.Production.ImageTag }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: frontend
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: tomcat-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: tomcat-app
    role: tomcat
